### ISSUE TITLE
通道管理API开发

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#14]
- [ ] 新建通道
   - [ ] 获取发起者组织的节点列表 
- [ ] 通道列表查询和条件过滤
- [ ] 节点加入通道

**Comment by bjwswang** [comment]
1. 新建通道API
示例: 
```yaml
apiVersion: ibp.com/v1beta1
kind: Channel
metadata:
  name: channel-sample
spec:  
  license:
    accept: true
  network: "network-sample3"
  members:
    - name: org1
    - name: org2
  description: "channel with org1 & org2"
```

参数详解：
- `network`:  用户管理的组织所在的网络 (required)
- `members`： 通道的成员列表(不区分initiator)  (required)
   -  至少有一个用户管理的组织 (required)
   - 其他的成员组织 (optional)
- `description` : 当前通道的描述信息 (optional)
