### ISSUE TITLE
策略管理API开发

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#29]
设计CRD: `EndorsePolicy` 

- [ ] 新建策略
- [ ] 查询策略
- [ ] 删除策略

**Comment by bjwswang** [comment]
## 1. 新建策略
参考: 
```
apiVersion: ibp.com/v1beta1
kind: EndorsePolicy
metadata:
  name: e-policy
spec:
  channel: channel-sample
  value: "OR('org1.member','org2.member')"
```
参数详解:
- `channel`: 此策略对应的channel
- `value`:策略详情内容
>NOTE: value的语法参考 https://hyperledger-fabric.readthedocs.io/en/latest/endorsement-policies.html#endorsement-policy-syntax






## 2. 更新策略


## 3. 删除策略
