### ISSUE TITLE
合约部署API开发

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#39]

**Comment by 0xff-dev** [comment]
## chaincode的状态
phase 一共有4种状态: 

- `ChaincodePending` 刚创建的 chaincode会处于这个状态。 表是等待投票，处于Pending的时候，对CR得任何改动，不会触发触发安装逻辑。
- `ChaincodeApproved` 投票通过，会执行chaincode的安装逻辑
- `ChaincodeUnapproved` 投票不通过，此后对CR的改动，不会触发安装逻辑
- `ChaincodeRunning` 表示已经安装成功，且相关的Pod已经正常运行。

---

## chaincode 安装过程中的状态
处于安装中的chaincode的 phase 一直是 `ChaincodeApproved`, 安装成功后会变成 `ChaincodeRunning`。  
chaincode 安装分成5个步骤，每一步都会将当前安装到哪一步写到 conditaions 里，**最后一条就是当前进度**。  

> **Note**
> 在某个阶段如果发生错误，`type`字段将会变成`ChaincodeError`, `nextStage` 字段表示下一次执行哪个阶段的操作。
> `chaincode.status.Conditions` 只会保留最近的10条记录。

### Pakcage
表示正处于 package 过程，成功后会向 `chaincode.status.conditions`添加一条记录

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: 'mkdir /demo: permission denied'
    nextStage: Packaged
    reason: 'mkdir /demo: permission denied'
    status: "False"
    type: ChaincodeError
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: chaincode package successfully
    nextStage: ""
    reason: ""
    status: "True"
    type: Packaged
  phase: ChaincodeApproved
```
根据最后一条记录，可以看出，当前Package阶段已经完成。


### install
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: 'some message'
    nextStage: Installed
    reason: 'some error message'
    status: "False"
    type: ChaincodeError
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: chaincode install successfully
    nextStage: ""
    reason: ""
    status: "True"
    type: Installed
  phase: ChaincodeApproved
```
根据最后一条记录，可以看出当前 chaincode 已经安装完成。

### approve

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: 'some message'
    nextStage: Approved
    reason: 'some error message'
    status: "False"
    type: ChaincodeError
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: chaincode approve successfully
    nextStage: ""
    reason: ""
    status: "True"
    type: Approved
  phase: ChaincodeApproved
```
这里最后一条表明，当前的chaincode已经被 channel 内的大部分组织同意。

### commit

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: 'some message'
    nextStage: Committed
    reason: 'some error message'
    status: "False"
    type: ChaincodeError
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: chaincode commit successfully
    nextStage: ""
    reason: ""
    status: "True"
    type: Committed
  phase: ChaincodeApproved
```
这里最后一条表明，当前的chaincode已经被 执行commit成功。

### check-running

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: 'some message'
    nextStage: Running
    reason: 'some error message'
    status: "False"
    type: ChaincodeError
  - lastTransitionTime: "2023-03-01T08:20:13Z"
    message: chaincode is running
    nextStage: ""
    reason: ""
    status: "True"
    type: Running
  phase: ChaincodeRunning
```

当检查所有的chaincode 的pod都正常运行后，conditions会添加一条`type=Running`的记录，同时 `chaincode.status.phase=ChaincodeRunning`

---

## 基本流程
基本的[部署流程](https://github.com/bestchains/fabric-operator/tree/main/config/samples#%E9%93%BE%E7%A0%81)


### 首先创建 EndorsePolicy
```yaml
apiVersion: ibp.com/v1beta1
kind: EndorsePolicy
metadata:
  name: e-policy
spec:
  channel: channel-sample 
  value: "OR('org1.member','org2.member')"
```
先创建这个，chaincode需要用到这个资源。

- channel 先写上，目前后段没用到。
- value 必须填写, 关乎策略的规则定义 [Endorsement policy syntax](https://hyperledger-fabric.readthedocs.io/en/latest/endorsement-policies.html#endorsement-policy-syntax)

### 创建 chaincode+proposal

#### chaincode
```yaml
apiVersion: ibp.com/v1beta1
kind: Chaincode
metadata:
  name: chaincode-sample
spec:  
  license:
    accept: true
  channel: channel-sample
  id: "chaincode1"
  label: "chaincode1"
  version: "v1"
  initRequired: false
  endorsePolicyRef:
    name: e-policy
  images:
    name: hyperledgerk8s/contract-go
    digest: sha256:6e9ce1685fed64558499ece990fa533fe7a35e2658bec7ad830a6fabdd99af7f
```

上面提到的字段都需要填写。
其中 id 字段的验证规则 `^[a-z][a-z0-9]{7,63}$`



#### proposal

```yaml
apiVersion: ibp.com/v1beta1
kind: Proposal
metadata:
  name: create-chaincode
  labels:
    bestchains.chaincode.delete.proposal: chaincode-sample
spec:
  federation: federation-sample
  policy: All
  initiatorOrganization: org1
  deployChaincode:
    chaincode: chaincode-sample
    members:
    - name: org1
      initiator: true
    - name: org2
```

这里需要注意 policy 与 channel 的proposal的policy是一致的。
> **Note**
> 这个label 一定要加上, 当chaincode删除的时候，会将关联的proposal也删除

### 升级 chaincode

升级 chaincode 也是需要通过投票，然后进入升级阶段

```yaml
apiVersion: ibp.com/v1beta1
kind: Proposal
metadata:
  name: create-chaincode-upgrade
  labels:
    bestchains.chaincode.delete.proposal: chaincode-sample
spec:
  federation: federation-sample
  policy: All
  initiatorOrganization: org1
  upgradeChaincode:
    chaincode: chaincode-sample
    members:
    - name: org1
      initiator: true
    - name: org2
    newVersion: v2
    newChaincodeImage:
      name: some-contract
      digest: sha256:aasfsdfafafsfsf
      pullSecret: <默认是Always>
```
投票通过后，会将chaincode的spec里面得version 和 image更新，进入chaincode 的安装逻辑。

> **Note**
> 这个label 一定要加上, 当chaincode删除的时候，会将关联的proposal也删除

### 删除 chaincode

目前只允许删除 `chaincode.status.phase=ChaincodeUnapproved`的

### 查询

chaincode创建会自动添加如下标签

- bestchains.chaincode.channel=<chaincode.spec.channel>
- bestchains.chaincode.id=<chaincode.spec.id>
- bestchains.chaincode.version=<chaincode.spec.version>
