### ISSUE TITLE
合约上传构建API开发

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#40]
- [ ] #43
- [ ] 新建合约(ChaincodeBuild)
- [ ] 删除合约(ChaincodeBuild)

**Comment by bjwswang** [comment]
> Note:相关CRD为 ChaincodeBuild

## 1. 新建合约

参考: https://github.com/bestchains/fabric-operator/blob/main/config/samples/ibp.com_v1beta1_chaincodebuild_minio.yaml
```
apiVersion: ibp.com/v1beta1
kind: ChaincodeBuild
metadata:
  name: chaincodebuild-sample-minio
spec:
  license:
    accept: true
  network: network-sample3
  id: go-contract
  version: "0.1"
  initiator: org1
  pipelineRunSpec:
    minio:
      bucket: "bestchains"
      object: "go-contract"
    dockerBuild:
      pushSecret: "dockerhub-secret"
      appImage: hyperledgerk8s/go-contract
      dockerfile: bestchains/go-contract/Dockerfile.optimized
      context: bestchains/go-contract
```
参数详解:
- `spec.network` : 为此合约构建所在的网络名称
- `spec.id` : 此合约id，为前端展示的合约名称
- `spec.version` : 此合约构建的版本，为前端展示的合约版本
- `spec.initiator` ： 上传发布此合约的用户组织
- `spec.pipelineRunSpec` : 合约构建的pipeline详情
    - `minio` :   (**代码来源为minio时**)  [参考](http://minio-console.172.22.96.209.nip.io/browser/bestchains/Z28tY29udHJhY3Qv)
        - `minio.bucket` :  (**代码来源为minio时**) 所在的minio bucket
        - `minio.object` :   (**代码来源为minio时**) 所在的minio object名称
    - `dockerBuild` 构建的详细配置
        - `dockerBuild.appImage` : 合约代码的镜像名称，规则为 {registry_url}/{chaincodebuild.name}:{chaincodebuild.spec.version}  
        - `dockerBuild.pushSecret` : 镜像推送时所用的secret (测试环境支持使用`dockerhub-secret`推送到内部镜像仓库)
        - `dockerBuild.dockerfile` : dockerfile相对object根目录(**{bucket}/{object}**)的路径
        - `dockerBuild.context`: 一般为object合约代码根目录(**{bucket}/{object}**)
       


## 2. 查询合约列表
